language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8'
- '6'
before_script:
- rm -rf node_modules
- yarn
script:
- yarn run test
- yarn run build
after_success:
- yarn run coverage
- yarn run semantic-release
branches:
  only:
  - master
